#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative '../lib/floss'
require 'optparse'

OptionParser.new do |parser|
  parser.banner = 'Easily manage floss repositories.'

  parser.on('-v', '--version', 'Floss current version') do
    print Floss::VERSION
  end

  parser.on('-g', '--grab', 'Grab floss projects') do
    Floss::Main.new(:grab).run
  end

  parser.on('-a', '--archive', 'Archive Floss projects') do
    Floss::Main.new(:archive).run
  end
end.parse!
