#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative '../lib/floss'

# and then, there was fire.
class Cli
  BASE = Floss::Utils.new

  program_desc 'Manage FLOSS Projects repositories.'
  version Floss::VERSION
  arguments :normal

  desc 'Archive Floss projects'
  command :archive do |c|
    c.action do
      Floss::Main.new(BASE, :archive).run
    end
  end

  desc 'Grab floss projects'
  command :grab do |c|
    c.action do
      Floss::Main.new(BASE, :grab).run
    end
  end
end

Cli.run(ARGV)
