#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative '../lib/info'
require_relative '../lib/qas'

module Cli
  attr_accessor :action, :args

  def self.options
    require 'optparse'

    OptionParser.new do |parser|
      parser.banner = Qas::DESCRIPTION

      parser.on('-v', '--version', 'project information') do
        print Qas::VERSION
        exit!
      end

      parser.on('-g', '--grab', 'grab floss projects') do
        @action = :grab
      end

      parser.on('-a', '--archive NAMES', Array, 'archive floss projects listed on NAMES') do |names|
        @names = names
        @action = :archive
      end
    end
  end

  def self.start
    options.parse! ['--help'] if ARGV.empty?

    begin
      options.parse!
    rescue OptionParser::MissingArgument
      puts <<~ERROR
        --archive NAMES

        Missing NAMES of projects!'
      ERROR
      exit!
    rescue OptionParser::InvalidOption
      options.parse! ['--help']
    end

    Qas::Main.new(@action, @names).run
  end
end

Cli.start
